[application]

# App name
name = "chapapp"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "../docs"

# The static resource path
asset_dir = "public"

[web.app]

# HTML title tag content
title = "chap_app"

# The application will be served at domain.com/my_application/, so we need to modify the base_path to the path where the application will be served
base_path = "ChapApp"

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
# reload_html = true

# Which files or dirs will be monitored
watch_path = ["src", "public"]

# Include style or script assets
[web.resource]

# CSS style file
style = ["./css/main.css"]

# Javascript code file
script = []

[web.resource.dev]

# Same as [web.resource], but for development servers

# CSS style file
style = []

# JavaScript files
script = []
